### ISSUE TITLE
financeへの対応について

### ISSUE THREAD

**Issue by ghost** [pCYSl5EDgo/Wahren#2]
本家で追加されている finance に対応していないかと思われるので、良ければ追加をお願いします。

https://www28.atwiki.jp/vahren_ency/pages/1028.html
>unit/class構造体に財政値を設定するfinance = 数値を追加しました。なお従来のcost=マイナス値を用いてるとcostの方が優先されてfinanceは無効になります。

**Comment by pCYSl5EDgo** [comment]
頑張って対応してみます。

**Comment by pCYSl5EDgo** [comment]
対応しました
