### ISSUE TITLE
全角空白の処理について

### ISSUE THREAD

**Issue by ghost** [pCYSl5EDgo/Wahren#3]
現在、name や detail などに設定した全角空白の記述が、本家環境と異なり反映されません。

例として、「Ａ国　一番隊隊長」のようなnameが設定されたユニットの場合、
UnitData の DisplayName が「Ａ国一番隊隊長」となっています。

良ければ対応をお願いします。

**Comment by pCYSl5EDgo** [comment]
全角空白を無視していましたか……
落ち着き次第確認します

**Comment by pCYSl5EDgo** [comment]
現在非公開ですが、Unity向けに完全に作り直しています。
全角空白の記述が反映されるようになりました。
